import {StyleSheet, Dimensions} from 'react-native';
import {FONTS} from '../../src/constants/fonts';
import {COLORS} from '../../src/constants/constants';

const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

export default StyleSheet.create({
  container: {
    flex: 1,
    height: windowHeight,
  },
  editToggleText: {
    padding: 8,
    fontSize: 16,
    color: COLORS.primary,
    fontWeight: 'bold',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#EEEEEE',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  bgButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
    marginRight: 10,
  },
  bgButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontFamily: FONTS.medium,
  },
  backButton: {
    padding: 8,
  },
  backButtonText: {
    fontSize: 18,
    color: COLORS.primary,
    fontWeight: 'bold',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.text,
  },
  scrollContainer: {
    minWidth: windowWidth,
    minHeight: windowHeight + 150,
  },
  workspaceContainer: {
    width: windowWidth,
    height: windowHeight + 150,
    position: 'relative',
    overflow: 'hidden',
  },
  backgroundImage: {
    opacity: 0.9,
    resizeMode: 'cover',
  },
  workspaceOverlay: {
    width: '100%',
    height: '100%',
    position: 'relative',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
  },
  tile: {
    position: 'absolute',
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#DDD',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  tileContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  tileText: {
    fontSize: 16,
    color: COLORS.text,
    textAlign: 'center',
  },
  noTilesContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  noTilesText: {
    fontSize: 18,
    color: '#888',
  },
  loadingText: {
    fontSize: 16,
    color: COLORS.text,
    textAlign: 'center',
    marginTop: 40,
  },
  linkContainer: {
    backgroundColor: '#F5F5F5',
    borderRadius: 8,
    width: '100%',
    minHeight: 0,
    padding: 10,
    flex: 0,
  },
  linkPreviewContainer: {
    width: '100%',
    flexDirection: 'column',
    flex: 0,
  },
  linkPreviewImage: {
    width: '100%',
    height: 120,
    borderRadius: 6,
    marginBottom: 4,
    backgroundColor: '#E0E0E0',
  },
  linkPreviewTitle: {
    fontSize: 16,
    fontFamily: FONTS.medium,
    color: COLORS.text,
    marginBottom: 2,
  },
  linkPreviewDescription: {
    fontSize: 12,
    fontFamily: FONTS.regular,
    color: '#666',
    marginBottom: 4,
    flexShrink: 1,
  },
  linkPreviewDomain: {
    fontSize: 11,
    fontFamily: FONTS.regular,
    color: '#888',
    marginTop: 4,
  },
  linkPreviewLoading: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  youtubeContainer: {
    backgroundColor: '#FEE2E2',
    borderRadius: 25,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  imageContainer: {
    backgroundColor: '#E6F7FF',
    borderRadius: 20,
    width: '100%',
    alignItems: 'center',
    overflow: 'hidden',
  },
  tileImage: {
    width: '100%',
    height: '100%',
  },
  imagePreviewContainer: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 8,
    padding: 12,
  },
  imagePreview: {
    width: '100%',
    height: 150,
    borderRadius: 4,
    marginBottom: 10,
  },
  selectImageButton: {
    backgroundColor: '#E6F7FF',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 4,
    alignItems: 'center',
  },
  selectImageButtonText: {
    color: COLORS.primary,
    fontFamily: FONTS.medium,
    fontSize: 14,
  },
  // Shape selection styles
  shapeSelectionContainer: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 12,
  },
  shapeSelectionTitle: {
    fontSize: 16,
    fontFamily: FONTS.medium,
    color: COLORS.text,
    marginBottom: 16,
  },
  shapeButtonsRow: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  shapeSelectionButton: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 8,
  },
  shapeSelectionText: {
    marginTop: 6,
    fontSize: 12,
    fontFamily: FONTS.medium,
    color: COLORS.text,
  },
  circleShapeIcon: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#E6F7FF',
    borderWidth: 1,
    borderColor: COLORS.primary,
  },
  squareShapeIcon: {
    width: 50,
    height: 50,
    backgroundColor: '#E6F7FF',
    borderWidth: 1,
    borderColor: COLORS.primary,
  },
  roundedShapeIcon: {
    width: 60,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#E6F7FF',
    borderWidth: 1,
    borderColor: COLORS.primary,
  },
  
  // Image cropping and shape selection styles
  cropContainer: {
    width: '100%',
    height: 250,
    marginBottom: 16,
    position: 'relative',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 8,
  },
  cropImageContainer: {
    width: '100%',
    height: '100%',
    overflow: 'hidden',
    position: 'relative',
  },
  cropImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  cropOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.3)',
  },
  cropFrame: {
    position: 'absolute',
    borderWidth: 2,
    borderColor: '#fff',
    backgroundColor: 'transparent',
  },
  cropFrameCircle: {
    borderRadius: 1000,
  },
  cropFrameSquare: {
    borderRadius: 0,
  },
  cropFrameRounded: {
    borderRadius: 16,
  },
  cropControls: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 8,
    marginBottom: 8,
  },
  cropShapeButton: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 4,
    backgroundColor: '#F0F0F0',
  },
  cropShapeButtonActive: {
    backgroundColor: COLORS.primary,
  },
  cropShapeButtonText: {
    fontSize: 12,
    fontFamily: FONTS.medium,
    color: COLORS.text,
  },
  cropShapeButtonTextActive: {
    color: '#FFFFFF',
  },
  cropHelperText: {
    textAlign: 'center',
    fontSize: 12,
    color: '#666',
    marginTop: 8,
    fontFamily: FONTS.regular,
  },
  linkText: {
    fontSize: 14,
    fontFamily: FONTS.medium,
    color: COLORS.primary,
    textDecorationLine: 'underline',
    textAlign: 'center',
  },
  tileControls: {
    position: 'absolute',
    top: -30,
    left: 10,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    opacity: 0.9,
    zIndex: 100,
  },
  tileControlButton: {
    marginRight: 10,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 3,
  },
  tileControlButtonText: {
    fontSize: 13,
    fontFamily: FONTS.medium,
    color: COLORS.text,
    fontWeight: '500',
  },
  resizeHandle: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.8)',
    borderTopLeftRadius: 8,
    zIndex: 10,
  },
  resizeHandleIcon: {
    width: 12,
    height: 12,
    borderBottomWidth: 2,
    borderRightWidth: 2,
    borderColor: COLORS.primary,
  },
  rotateHandle: {
    position: 'absolute',
    right: 0,
    top: 0,
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.8)',
    borderBottomLeftRadius: 8,
    zIndex: 10,
  },
  rotateHandleIcon: {
    width: 12,
    height: 12,
    borderTopWidth: 2,
    borderRightWidth: 2,
    borderColor: COLORS.primary,
  },
  addBtn: {
    position: 'absolute',
    bottom: 24,
    right: 24,
    zIndex: 10,
  },
  addBtnInner: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 5,
  },
  addBtnText: {
    fontSize: 28,
    fontFamily: FONTS.bold,
    color: '#FFFFFF',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: 320,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  modalTitle: {
    fontSize: 20,
    fontFamily: FONTS.bold,
    color: COLORS.text,
    marginBottom: 16,
    textAlign: 'center',
  },
  typeRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 16,
  },
  typeBtn: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: '#F0F0F0',
    marginHorizontal: 4,
  },
  typeBtnActive: {
    backgroundColor: COLORS.primary,
  },
  typeBtnText: {
    fontFamily: FONTS.medium,
    color: COLORS.text,
  },
  typeBtnTextActive: {
    color: '#FFFFFF',
  },
  input: {
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
    fontFamily: FONTS.regular,
    fontSize: 16,
    color: COLORS.text,
    minHeight: 80,
  },
  modalButtonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  modalCancelBtn: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    backgroundColor: '#F0F0F0',
    marginRight: 8,
    alignItems: 'center',
  },
  modalCancelBtnText: {
    fontFamily: FONTS.medium,
    color: COLORS.text,
  },
  modalAddBtn: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    backgroundColor: COLORS.primary,
    marginLeft: 8,
    alignItems: 'center',
  },
  modalAddBtnText: {
    fontFamily: FONTS.medium,
    color: '#FFFFFF',
  },
  
  // Background selector styles
  bgSelectorContainer: {
    width: 320,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  bgOptionsList: {
    marginVertical: 16,
  },
  bgOptionButton: {
    width: 130,
    height: 130,
    margin: 8,
    borderRadius: 8,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'transparent',
    backgroundColor: '#F0F0F0',
  },
  bgOptionButtonActive: {
    borderColor: COLORS.primary,
  },
  bgOptionImage: {
    width: '100%',
    height: 100,
    resizeMode: 'cover',
  },
  bgOptionText: {
    textAlign: 'center',
    paddingVertical: 6,
    fontSize: 14,
    fontFamily: FONTS.medium,
    color: COLORS.text,
  },
});
