source 'https://rubygems.org'

gem 'cocoapods', '~> 1.16'
gem 'fastlane', '~> 2.227.1'
gem 'fastlane-plugin-firebase_app_distribution'
gem 'xcodeproj'
gem 'abbrev' # Required for Ruby 3.4+
gem 'json', '~> 2.12.0'
gem 'aws-sdk-s3', '~> 1.186.0'
gem 'security', '~> 0.1.3'
gem 'xcpretty', '~> 0.4.1'
gem 'rouge', '~> 3.28.0'
gem 'logger', '~> 1.7.0'
gem 'signet', '~> 0.20.0'
