default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # Ensure that your git status is clean
    ensure_git_status_clean

    # Increment build number
    increment_build_number(xcodeproj: "Rewire.xcodeproj")
    
    # Update CocoaPods
    cocoapods(
      clean_install: true,
      podfile: "./Podfile"
    )
    
    # Build the app
    build_app(
      workspace: "Rewire.xcworkspace",
      scheme: "Rewire",
      clean: true,
      export_method: "development",
      skip_profile_detection: true,
      export_options: {
        method: "development",
        signingStyle: "automatic",
        teamID: "4LHEX387VL"
      },
      silent: false,
      output_directory: "./build",
      output_name: "Rewire.ipa"
    )
    
    # Upload to TestFlight
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
    
    # Commit the version bump
    commit_version_bump(
      message: "Build version bump by fastlane",
      xcodeproj: "Rewire.xcodeproj"
    )
    
    # Push the commit
    push_to_git_remote
  end
  
  desc "Register new devices"
  lane :add_devices do
    register_devices(
      devices_file: "./fastlane/devices.txt"
    )
    match(type: "development", force_for_new_devices: true)
    match(type: "adhoc", force_for_new_devices: true)
  end
  
  desc "Sync certificates and profiles"
  lane :sync_signing do
    match(type: "appstore")
    match(type: "development")
    match(type: "adhoc")
  end
end
